### ISSUE TITLE
npm install tries to download inexistent beta version

### ISSUE THREAD

**Issue by ales004** [rt2zz/redux-persist#213] opened 2016-11-17 11:03 UTC
If you write:
npm install --save redux-persist

npm tries to download the version: 
https://registry.npmjs.org/redux-persist/-/redux-persist-4.0.0-beta1.tgz

that does not exist.

We had to set the version to 4.0.0-alpha7 for it to run.

**Comment by hugohow** [comment] 2016-11-17 13:15
+1

**Comment by po-jo** [comment] 2016-11-17 13:22
This is a duplicate of : https://github.com/rt2zz/redux-persist/issues/212, isn't it ?

**Comment by marvinhagemeister** [comment] 2016-11-17 14:26
Agreed, I'm closing this in favor of #212

**Closed by marvinhagemeister** 2016-11-17 14:26 UTC
