### ISSUE TITLE
fetch failed https://registry.npmjs.org/redux-persist/-/redux-persist-4.0.0-beta1.tgz

### ISSUE THREAD

**Issue by rahulpatidarrails** [rt2zz/redux-persist#214] opened 2016-11-17 13:44 UTC
I am unable to install redux-persist.

Please have a look on log
```

npm install redux-persist --save
npm ERR! fetch failed https://registry.npmjs.org/redux-persist/-/redux-persist-4.0.0-beta1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/redux-persist/-/redux-persist-4.0.0-beta1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/redux-persist/-/redux-persist-4.0.0-beta1.tgz
npm ERR! Linux 3.13.0-63-generic
npm ERR! argv "/home/rails/.nvm/versions/node/v6.0.0/bin/node" "/home/rails/.nvm/versions/node/v6.0.0/bin/npm" "install" "redux-persist" "--save"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! fetch failed with status code 404
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rails/work/vijay/react/react_support_system/npm-debug.log

```

**Comment by junshengpierre** [comment] 2016-11-17 14:25
+1

**Comment by po-jo** [comment] 2016-11-17 14:29
same as https://github.com/rt2zz/redux-persist/issues/212

**Comment by marvinhagemeister** [comment] 2016-11-17 14:30
Closing because this is a duplicate of #212 .

**Closed by marvinhagemeister** 2016-11-17 14:30 UTC
